### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by FindHao** [FindHao/nvsmi#1]
- [x] add compute processes
- [x] fix known bug `nvml error: Insufficient Size`
- [x] format output
- [x] better memory management
